version: 2
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
jobs:
  flutter_test:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run: flutter doctor
      - run: cd e_bulletin; flutter test;
  
  flutter_build:
    docker: 
      - image: cirrusci/flutter:latest
    
    steps:
      - checkout
      - run: flutter doctor
      - run: cd e_bulletin; flutter build apk;

  html_test:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: cd public; npm test;
      


workflows:
  version: 2
  build-and-test:
    jobs:
      - flutter_test
      - flutter_build
      - html_test
      
