version: 2
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
jobs:
  flutter_test:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run: flutter doctor
      - run: cd e_bulletin; flutter test;

  flutter_build:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run: flutter doctor
      - run: cd e_bulletin; flutter build apk;

  html_test:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run: cd public; npm install; npm test;

  html_deploy:
    working_directory: ~/public/
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build-and-test:
    jobs:
      - flutter_test
      - flutter_build
      - html_test
      - html_deploy:
          requires:
            - html_test
