version: 2
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest

    steps:
      - checkout
      - run: flutter doctor
      - run: cd e_bulletin; flutter test;
      


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      
