name: Dart CI

on: 
  push:
    branches: 
      - master
      - Development

jobs:
  build:

    runs-on: [macos-latest]

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cd e_bulletin
        pub get
    - name: Run tests
      run: pub run test
    - name: Test Compile
      run: flutter build ios
